# Use the official Node.js runtime as the base image
FROM node:18-alpine

# Install dependencies only when needed
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json package-lock.json* ./
RUN npm ci

# Copy source code
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
ENV NEXT_TELEMETRY_DISABLED 1

# Set environment variables for development
ENV NODE_ENV=development
ENV PORT=3001
ENV HOSTNAME="0.0.0.0"

EXPOSE 3001

# Run the development server
CMD ["npm", "run", "dev"]
