import type { PostIndexEntry } from './post-metadata';

export const hardcodedPosts: PostIndexEntry[] = [
  {
    slug: "cemetery-management-application-gps-mapping-ar-integration-and-autonomous-maintenance-for-funeral-homes",
    title: "Cemetery Management Application: GPS Mapping, AR Integration, and Autonomous Maintenance for Funeral Homes",
    publishedDate: "2025-09-28T00:00:00.000Z",
    modifiedDate: "2025-09-28T00:00:00.000Z",
    lastReviewedDate: "2025-09-28T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Technology",
    series: "",
    topics: ["Development & Tools", "AI & Automation"],
    tags: ["cemetery-app", "gps-mapping", "ar-maintenance", "autonomous-drones", "revenant-hollow"],
    keywords: ["cemetery management software", "GPS grave mapping", "AR cemetery maintenance", "autonomous mowers", "drone cemetery patrols", "UGV terrain mapping", "funeral home CRM", "Revenant Hollow", "location-based AR", "mixed reality experiences"],
    wordCount: 1273,
    fileSize: 10830,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "revisiting-old-code-lessons-in-growth-enterprise-vs-startup-mindsets-and-ai-driven-infrastructure-evolution",
    title: "Revisiting Old Code: Lessons in Growth, Enterprise vs. Startup Mindsets, and AI-Driven Infrastructure Evolution",
    publishedDate: "2025-09-27T00:00:00.000Z",
    modifiedDate: "2025-09-27T00:00:00.000Z",
    lastReviewedDate: "2025-09-27T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Career",
    series: "",
    topics: ["Career & Professional Development", "Development & Tools"],
    tags: ["code-quality", "infrastructure-as-code", "generative-ai", "enterprise-vs-startup", "devops-practices"],
    keywords: ["code quality", "infrastructure as code", "generative AI", "enterprise vs startup", "DevOps practices", "cloud architecture", "security practices", "startup agility", "terraform", "AI-assisted development"],
    wordCount: 1856,
    fileSize: 15890,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "lessons-from-mentors-enterprise-insights-and-personal-reflections-from-urban-dynamics",
    title: "Lessons from Mentors: Enterprise Insights and Personal Reflections from Urban Dynamics",
    publishedDate: "2025-09-24T00:00:00.000Z",
    modifiedDate: "2025-09-24T00:00:00.000Z",
    lastReviewedDate: "2025-09-24T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Career",
    series: "",
    topics: ["Career & Professional Development", "Development & Tools"],
    tags: ["enterprise-devops", "mentorship", "identity-access-management", "startup-enterprise", "personal-reflection"],
    keywords: ["enterprise DevOps", "identity management", "single sign-on", "mentorship", "startup culture", "enterprise contracts", "networking security", "personal growth", "AI-assisted development", "creative ideation"],
    wordCount: 1423,
    fileSize: 12150,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "building-a-generative-framework-evolving-ai-coding-agents-and-human-ai-collaboration",
    title: "Building a Generative Framework: Evolving AI Coding Agents and Human-AI Collaboration",
    publishedDate: "2025-09-23T00:00:00.000Z",
    modifiedDate: "2025-09-23T00:00:00.000Z",
    lastReviewedDate: "2025-09-23T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Technology",
    series: "",
    topics: ["AI & Automation", "Development & Tools"],
    tags: ["generative-framework", "coding-agents", "ai-autonomy", "human-ai-collaboration", "software-development"],
    keywords: ["generative framework", "coding agents", "AI autonomy", "human-AI collaboration", "software development", "LLM productivity", "prompt engineering", "agentic AI", "AI training data", "heuristic for AI use"],
    wordCount: 1654,
    fileSize: 14120,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "the-power-of-flat-files-in-blogging-repurposing-coding-tools-for-content-creation-and-ai-optimization",
    title: "The Power of Flat Files in Blogging: Repurposing Coding Tools for Content Creation and AI Optimization",
    publishedDate: "2025-09-22T00:00:00.000Z",
    modifiedDate: "2025-09-22T00:00:00.000Z",
    lastReviewedDate: "2025-09-22T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Technology",
    series: "",
    topics: ["AI & Automation", "Development & Tools"],
    tags: ["flat-files", "blogging", "jamstack", "nextjs", "ai-content-creation"],
    keywords: ["flat files", "blogging", "Jamstack", "Next.js", "AI content creation", "coding agents", "generative search", "YAML frontmatter", "Markdown", "IDE indexing", "SEO schema updates", "human-AI collaboration"],
    wordCount: 1789,
    fileSize: 15230,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "troubleshooting-n8n-workflows-integrated-with-supabase-vapi-and-lovable-for-ai-driven-sales-automation",
    title: "Troubleshooting n8n Workflows Integrated with Supabase, Vapi, and Lovable for AI-Driven Sales Automation",
    publishedDate: "2025-09-21T00:00:00.000Z",
    modifiedDate: "2025-09-21T00:00:00.000Z",
    lastReviewedDate: "2025-09-21T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Technology",
    series: "",
    topics: ["AI & Automation", "Development & Tools"],
    tags: ["n8n", "workflow-automation", "supabase", "vapi", "lovable", "ai-sales"],
    keywords: ["n8n workflows", "Supabase integration", "Vapi AI", "Lovable platform", "sales automation", "AI-driven workflows", "troubleshooting", "workflow debugging", "API integration", "automation tools"],
    wordCount: 1345,
    fileSize: 11540,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "building-drum-note-ai-powered-drum-transcription-kit-generation-and-hands-on-marketing-with-rendercom",
    title: "Building Drum Note: AI-Powered Drum Transcription, Kit Generation, and Hands-On Marketing with Render.com",
    publishedDate: "2025-09-20T00:00:00.000Z",
    modifiedDate: "2025-09-20T00:00:00.000Z",
    lastReviewedDate: "2025-09-20T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Technology",
    series: "",
    topics: ["AI & Automation", "Development & Tools", "Marketing & Business"],
    tags: ["drum-transcription", "ai-music", "render-com", "marketing", "audio-analysis"],
    keywords: ["drum transcription", "AI music analysis", "Render.com deployment", "hands-on marketing", "audio processing", "music technology", "AI-powered tools", "drum kit generation", "audio analysis", "music software"],
    wordCount: 1567,
    fileSize: 13380,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "replit-test-drive",
    title: "Exploring No-Code Development with Replit: A Professional Analysis",
    publishedDate: "2025-09-19T00:00:00.000Z",
    modifiedDate: "2025-09-19T00:00:00.000Z",
    lastReviewedDate: "2025-09-19T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Technology",
    series: "",
    topics: ["Development & Tools"],
    tags: ["replit", "no-code", "development-tools", "coding-platform", "analysis"],
    keywords: ["Replit", "no-code development", "coding platform", "development tools", "professional analysis", "coding environment", "collaborative coding", "online IDE", "development workflow"],
    wordCount: 1234,
    fileSize: 10560,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "the-last-cycle-why-founder-engineer-partnerships-are-nearing-their-end",
    title: "The Last Cycle: Why Founder-Engineer Partnerships Are Nearing Their End",
    publishedDate: "2025-09-18T00:00:00.000Z",
    modifiedDate: "2025-09-18T00:00:00.000Z",
    lastReviewedDate: "2025-09-18T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Business",
    series: "",
    topics: ["Career & Professional Development", "Marketing & Business"],
    tags: ["founder-engineer", "partnerships", "startup-culture", "business-strategy", "career-development"],
    keywords: ["founder-engineer partnerships", "startup culture", "business strategy", "career development", "partnership dynamics", "startup evolution", "business relationships", "entrepreneurship", "professional partnerships"],
    wordCount: 1456,
    fileSize: 12450,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "revenant-hollow-integrating-technology-into-location-based-horror-experiences",
    title: "Revenant Hollow: Integrating Technology into Location-Based Horror Experiences",
    publishedDate: "2025-09-17T00:00:00.000Z",
    modifiedDate: "2025-09-17T00:00:00.000Z",
    lastReviewedDate: "2025-09-17T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Technology",
    series: "",
    topics: ["AI & Automation", "Development & Tools"],
    tags: ["revenant-hollow", "location-based", "horror-experiences", "technology-integration", "mixed-reality"],
    keywords: ["Revenant Hollow", "location-based experiences", "horror technology", "mixed reality", "technology integration", "immersive experiences", "location-based entertainment", "horror experiences", "technology in entertainment"],
    wordCount: 1678,
    fileSize: 14320,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "the-jumpstarter-a-5-point-framework-to-align-value-and-passion",
    title: "The Jumpstarter: A 5-Point Framework to Align Value and Passion",
    publishedDate: "2025-09-16T00:00:00.000Z",
    modifiedDate: "2025-09-16T00:00:00.000Z",
    lastReviewedDate: "2025-09-16T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Career",
    series: "",
    topics: ["Career & Professional Development"],
    tags: ["jumpstarter", "framework", "value-alignment", "passion", "career-development"],
    keywords: ["Jumpstarter framework", "value alignment", "passion", "career development", "professional growth", "career framework", "personal development", "career strategy", "professional alignment"],
    wordCount: 1323,
    fileSize: 11310,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "enhancing-seo-on-my-company-landing-site-with-ai-agents",
    title: "Enhancing SEO on My Company Landing Site with AI Agents",
    publishedDate: "2025-09-15T00:00:00.000Z",
    modifiedDate: "2025-09-15T00:00:00.000Z",
    lastReviewedDate: "2025-09-15T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Marketing",
    series: "",
    topics: ["AI & Automation", "Development & Tools", "Marketing & Business"],
    tags: ["seo", "ai-agents", "landing-site", "marketing", "automation"],
    keywords: ["SEO enhancement", "AI agents", "landing site optimization", "marketing automation", "SEO tools", "AI-powered SEO", "website optimization", "digital marketing", "SEO strategy"],
    wordCount: 1489,
    fileSize: 12720,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "scaling-novelty-with-an-agentic-blog-bot",
    title: "Scaling Novelty with an Agentic Blog Bot",
    publishedDate: "2025-09-14T00:00:00.000Z",
    modifiedDate: "2025-09-14T00:00:00.000Z",
    lastReviewedDate: "2025-09-14T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Technology",
    series: "",
    topics: ["AI & Automation", "Marketing & Business"],
    tags: ["agentic-blog-bot", "ai-automation", "content-creation", "scaling", "novelty"],
    keywords: ["agentic blog bot", "AI automation", "content creation", "scaling novelty", "blog automation", "AI content generation", "automated blogging", "content scaling", "AI agents"],
    wordCount: 1567,
    fileSize: 13380,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "building-an-effective-web-presence-for-professional-validation",
    title: "Building an Effective Web Presence for Professional Validation",
    publishedDate: "2025-09-13T00:00:00.000Z",
    modifiedDate: "2025-09-13T00:00:00.000Z",
    lastReviewedDate: "2025-09-13T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Career",
    series: "",
    topics: ["Career & Professional Development", "Marketing & Business"],
    tags: ["web-presence", "professional-validation", "career-development", "personal-branding", "online-presence"],
    keywords: ["web presence", "professional validation", "career development", "personal branding", "online presence", "professional image", "career advancement", "digital presence", "professional growth"],
    wordCount: 1345,
    fileSize: 11540,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "transitioning-from-cable-contracting-to-freelance-web-development-a-career-pivot",
    title: "Transitioning from Cable Contracting to Freelance Web Development: A Career Pivot",
    publishedDate: "2025-09-12T00:00:00.000Z",
    modifiedDate: "2025-09-12T00:00:00.000Z",
    lastReviewedDate: "2025-09-12T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Career",
    series: "",
    topics: ["Career & Professional Development"],
    tags: ["career-pivot", "cable-contracting", "freelance", "web-development", "career-transition"],
    keywords: ["career pivot", "cable contracting", "freelance web development", "career transition", "professional change", "career development", "freelancing", "web development", "career transformation"],
    wordCount: 1423,
    fileSize: 12150,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "early-adventures-in-freelance-web-development-lessons-from-the-wordpress-era",
    title: "Early Adventures in Freelance Web Development: Lessons from the WordPress Era",
    publishedDate: "2025-09-11T00:00:00.000Z",
    modifiedDate: "2025-09-11T00:00:00.000Z",
    lastReviewedDate: "2025-09-11T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Career",
    series: "",
    topics: ["Career & Professional Development", "Development & Tools"],
    tags: ["freelance", "web-development", "wordpress", "early-career", "lessons-learned"],
    keywords: ["freelance web development", "WordPress era", "early career", "lessons learned", "web development history", "freelancing", "career development", "web development", "professional growth"],
    wordCount: 1567,
    fileSize: 13380,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "my-first-tech-job-the-evolution-of-the-docworks-emr-system-2011-2013",
    title: "My First Tech Job: The Evolution of the DocWorks EMR System (2011-2013)",
    publishedDate: "2025-09-10T00:00:00.000Z",
    modifiedDate: "2025-09-10T00:00:00.000Z",
    lastReviewedDate: "2025-09-10T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Career",
    series: "",
    topics: ["Career & Professional Development", "Development & Tools"],
    tags: ["first-tech-job", "docworks", "emr-system", "healthcare-software", "career-development"],
    keywords: ["first tech job", "DocWorks EMR", "healthcare software", "career development", "EMR system", "healthcare technology", "software development", "career history", "professional growth"],
    wordCount: 1678,
    fileSize: 14320,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "intro-to-linux-how-i-stayed-in-the-dev-game-while-too-broke-to-buy-a-pc",
    title: "Intro to Linux: How I Stayed in the Dev Game While Too Broke to Buy a PC",
    publishedDate: "2025-09-09T00:00:00.000Z",
    modifiedDate: "2025-09-09T00:00:00.000Z",
    lastReviewedDate: "2025-09-09T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Career",
    series: "",
    topics: ["Career & Professional Development", "Development & Tools"],
    tags: ["linux", "development", "career-development", "personal-story", "technology"],
    keywords: ["Linux", "development", "career development", "personal story", "technology", "open source", "development tools", "career growth", "professional development"],
    wordCount: 1234,
    fileSize: 10560,
    fileModified: "2025-10-01T14:21:15.777Z"
  },
  {
    slug: "my-first-steps-into-coding",
    title: "My First Steps into Coding: A Biographical Journey",
    publishedDate: "2025-09-08T00:00:00.000Z",
    modifiedDate: "2025-09-08T00:00:00.000Z",
    lastReviewedDate: "2025-09-08T00:00:00.000Z",
    isDraft: false,
    isFeatured: true,
    priority: 8,
    category: "Career",
    series: "",
    topics: ["Career & Professional Development"],
    tags: ["first-steps", "coding", "biographical", "career-development", "personal-journey"],
    keywords: ["first steps", "coding", "biographical journey", "career development", "personal journey", "programming", "career growth", "professional development", "coding journey"],
    wordCount: 1456,
    fileSize: 12450,
    fileModified: "2025-10-01T14:21:15.777Z"
  }
];
